lib/events_app_web/router.ex
defmodule EventsAppWeb.Router do
  use EventsAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsAppWeb.Plugs.FetchUser 
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EventsAppWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController
    resources "/users", UserController
    get "/users/photo/:id", UserController, :photo
    resources "/comments", CommentController
    resources "/invites", InviteController
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", EventsAppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsAppWeb.Telemetry
    end
  end
end

lib/events_app_web/templates/page/index.html.eex
<%= if have_current_user?(@conn) do %>

<div class="row">
  <div class="col">
      <p><%= link "Create A New Event", to: Routes.event_path(@conn, :new) %></p>
   
  </div>
</div>

<!-- taken from Prof Nat Tuck's lecture notes -->

<h1>Your Events</h1>

<div class="row">
  <%= for event <- @events do %>
    <%= if current_user_id?(@conn, event.user_id) do %>
      <div class="col-sm-4 card">
        <div class="card-title">
          <p class="card-text"><%=event.name %></p>
        </div>

        <div class="card-body">
          <p class="card-text"><%=event.body %></p>
          <p class="card-text"><%=event.date %></p>
  	  <p class="card-text">Event made by <%=event.user.name %></p>
          <%= link "view", to: Routes.event_path(@conn, :show, event) %>
        </div>
    <% end %>

    </div>
  <% end %>
</div>

<% else %>
  <p> Log in to create a new event and invite your friends! </p>
<% end %>